services:
  todo-web:
    container_name: todo-web
    image: rx90/todo-app
    build: ./
    command: ./wait-for-postgres.sh db ./todo-app
    depends_on:
      - db
    environment:
      - DB_PASSWORD=password
    ports:
      - 8000:8000

  db:
    container_name: todo-db
    image: postgres:15-alpine
    restart: on-failure
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432